# Pythonスクリプト名（拡張子なし）
VERSION := $(shell cat VERSION)
TARGET=rsssummarizer
ZIP_NAME := $(TARGET)-$(VERSION).zip

# PyInstallerのオプション
PYINSTALLER_OPTS=--onefile --name $(TARGET)

# デフォルトターゲット
.PHONY: all clean

all: build

# PyInstallerを使ってEXEを作成
build:
	pyinstaller $(PYINSTALLER_OPTS) $(TARGET).py

# ビルド成果物を削除
clean:
	rm -rf build dist *.spec

zip:
	7z a $(ZIP_NAME) ./dist/$(TARGET).exe ./$(TARGET).env
